version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - n 14.19.1
      - node -v
      - pip install --upgrade pip
      - pip install --upgrade awscli
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run $BUILD_MODE
      - npm run $GENERATE_MODE
  post_build:
    commands:
      - aws s3 sync ./dist $S3_BUCKET
      - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths '/*'
